"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Loader2, Package, RefreshCw } from "lucide-react";
import { useSupplyChain } from "@/hooks/useSupplyChain";

interface CreateProductFormProps {
  onSuccess?: () => void;
  onCancel?: () => void;
}

export function CreateProductForm({ onSuccess, onCancel }: CreateProductFormProps) {
  const { produceItemByFarmer, isPending } = useSupplyChain();

  const [formData, setFormData] = useState({
    productName: "",
    description: "",
    ipfsHash: "",
    price: "",
    shippingDeadline: "",
    receivingDeadline: "",
  });

  const generateMockHash = () => {
    // Simulate IPFS hash generation
    const mockHash = "Qm" + Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
    setFormData(prev => ({ ...prev, ipfsHash: mockHash }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.productName || !formData.description || !formData.ipfsHash || !formData.price || !formData.shippingDeadline) {
      alert("Please fill all required fields");
      return;
    }

    try {
      const productCode = BigInt(0); // Auto-generated by contract
      const shippingDeadlineBigInt = BigInt(
        Math.floor(new Date(formData.shippingDeadline).getTime() / 1000)
      );

      await produceItemByFarmer(
        productCode,
        formData.ipfsHash,
        formData.price,
        shippingDeadlineBigInt
      );

      // Reset form or call success callback
      if (onSuccess) onSuccess();
    } catch (error) {
      console.error("Failed to create product:", error);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="space-y-2">
          <Label htmlFor="productName">Product Name *</Label>
          <Input
            id="productName"
            value={formData.productName}
            onChange={(e) => setFormData({ ...formData, productName: e.target.value })}
            placeholder="e.g. Organic Tomatoes"
            required
          />
          <p className="text-xs text-muted-foreground">
            Name of the agricultural product
          </p>
        </div>

        <div className="space-y-2">
          <Label htmlFor="price">Price (ETH) *</Label>
          <Input
            id="price"
            type="number"
            step="0.001"
            min="0.001"
            max="1000"
            value={formData.price}
            onChange={(e) => setFormData({ ...formData, price: e.target.value })}
            placeholder="0.05"
            required
          />
          <p className="text-xs text-muted-foreground">
            Range: 0.001 - 1000 ETH
          </p>
        </div>

        <div className="space-y-2 md:col-span-2">
          <Label htmlFor="description">Description *</Label>
          <Textarea
            id="description"
            value={formData.description}
            onChange={(e) => setFormData({ ...formData, description: e.target.value })}
            placeholder="Detailed description of the product..."
            className="h-20"
            required
          />
        </div>

        <div className="space-y-2 md:col-span-2">
          <Label htmlFor="ipfsHash">IPFS Hash *</Label>
          <div className="flex space-x-2">
            <Input
              id="ipfsHash"
              value={formData.ipfsHash}
              onChange={(e) => setFormData({ ...formData, ipfsHash: e.target.value })}
              placeholder="Qm..."
              required
            />
            <Button type="button" variant="outline" size="icon" onClick={generateMockHash} title="Generate Mock Hash">
              <RefreshCw className="h-4 w-4" />
            </Button>
          </div>
          <p className="text-xs text-muted-foreground">
            Metadata hash for product information
          </p>
        </div>

        <div className="space-y-2">
          <Label htmlFor="shippingDeadline">Shipping Deadline *</Label>
          <Input
            id="shippingDeadline"
            type="datetime-local"
            value={formData.shippingDeadline}
            onChange={(e) => setFormData({ ...formData, shippingDeadline: e.target.value })}
            required
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="receivingDeadline">Receiving Deadline</Label>
          <Input
            id="receivingDeadline"
            type="datetime-local"
            value={formData.receivingDeadline}
            onChange={(e) => setFormData({ ...formData, receivingDeadline: e.target.value })}
          />
          <p className="text-xs text-muted-foreground">
            Optional
          </p>
        </div>
      </div>

      <div className="flex justify-end space-x-2 pt-4">
        {onCancel && (
          <Button type="button" variant="outline" onClick={onCancel} disabled={isPending}>
            Cancel
          </Button>
        )}
        <Button type="submit" disabled={isPending}>
          {isPending ? (
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          ) : (
            <Package className="mr-2 h-4 w-4" />
          )}
          {isPending ? "Creating..." : "Create Product"}
        </Button>
      </div>
    </form>
  );
}
